language: android
dist: trusty
android:
  components:
    - android-29
    - android-21
    - build-tools-29.0.2
    - sys-img-armeabi-v7a-android-21

env:
  global:
    - MALLOC_ARENA_MAX=2

sudo: required

before_install:
  - yes | sdkmanager "platforms;android-29"
  - yes | sdkmanager "build-tools;29.0.2"

before_script:
  - chmod +x gradlew
  - echo no | android create avd --force -n test -t android-21 --abi armeabi-v7a -s "768x1280"
  - emulator -avd test -no-audio -no-window &
  - adb wait-for-device
  - adb shell input keyevent 82 &

script: ./gradlew :app:build :app:connectedDebugAndroidTest