language: android
dist: trusty
android:
  components:
    - android-29
    - android-26
    - build-tools-29.0.2
    - sys-img-x86-google_apis-26

env:
  global:
    - MALLOC_ARENA_MAX=2

sudo: required

before_install:
  - yes | sdkmanager "platforms;android-29"
  - yes | sdkmanager "build-tools;29.0.2"

script:
- ./gradlew clean test build