/**
 * Weather Server
 * This is a weather data server. For each point on the globe, we provide historical, current and forecasted weather data via light-speed APIs.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models

import io.swagger.client.models.CurrentWeatherMain
import io.swagger.client.models.Location
import io.swagger.client.models.WeatherReport
import io.swagger.client.models.Wind

/**
 * 
 * @param coord 
 * @param weather 
 * @param visibility Visibility distance
 * @param wind 
 * @param main 
 */
data class CurrentWeather (

    val coord: Location? = null,
    val weather: kotlin.Array<WeatherReport>? = null,
    /* Visibility distance */
    val visibility: Double? = null,
    val wind: Wind? = null,
    val main: CurrentWeatherMain? = null
) {
}