/**
 * Weather Server
 * This is a weather data server. For each point on the globe, we provide historical, current and forecasted weather data via light-speed APIs.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models


/**
 * Humidity, %
 * @param day  Day temperature. Unit Default: Kelvin, Metric: Celsius, Imperial: Fahrenheit.
 * @param min Min daily temperature. Unit Default: Kelvin, Metric: Celsius, Imperial: Fahrenheit.
 * @param max Max daily temperature. Unit Default: Kelvin, Metric: Celsius, Imperial: Fahrenheit.
 */
data class DailyTemperature (

    /*  Day temperature. Unit Default: Kelvin, Metric: Celsius, Imperial: Fahrenheit. */
    val day: Double,
    /* Min daily temperature. Unit Default: Kelvin, Metric: Celsius, Imperial: Fahrenheit. */
    val min: Double,
    /* Max daily temperature. Unit Default: Kelvin, Metric: Celsius, Imperial: Fahrenheit. */
    val max: Double
) {
}